### ISSUE TITLE
[feature request] guild chatbot

### ISSUE THREAD

**Issue by oodvg** [CalmGuild/CalmBot#4]
adding a guild chatbot between hypixel and discord. some of the top guilds have this. It allows coms between guild members that are even offline on hypixel!

**Comment by Miqhtiedev** [comment]
> adding a guild chatbot between hypixel and discord. some of the top guilds have this. It allows coms between guild members that are even offline on hypixel!

We already have a repo under this organization for the purpose of logging chat activity with a mc bot however a decision was made by guild staff to not include a bridge between discord and hypixel as that may clutter the guild chat. In addition to that there is always the risk of it getting banned if a guild member abuses it and says some muteable words.
